update hooks/build with fixes from llama-env

diff --git a/hooks/build b/hooks/build
--- a/hooks/build
+++ b/hooks/build
@@ -11,6 +11,18 @@ echo "[***] Build hook running"
 
 REPO="$(awk -F'/' '{print $(NF-1) "/" $NF}' <<<"${DOCKER_REPO}")"
 NAME="${REPO}:${DOCKER_TAG}"
+last_dockerfile=''
+
+cleanup(){
+    if [[ -f "${last_dockerfile}" ]]; then
+        echo "Deleting old Dockerfile at ${last_dockerfile}"
+        rm "${last_dockerfile}"
+    else
+        echo "No old Dockerfile found to delete."
+    fi
+}
+
+trap "cleanup" EXIT
 
 # See if we have changed anything since the last tag.
 # If not, just reuse the old image.
@@ -18,15 +30,27 @@ if current_tag="`git describe --tags`"; then
     echo Current tag: $current_tag
     if last_tag="`git describe --abbrev=0 "$current_tag"^`"; then
         echo Last tag: $last_tag
-        git fetch origin && echo Fetched from origin || echo Could not fetch
+        if git show "$last_tag"^:${DOCKERFILE_PATH} >/dev/null; then
+            echo Last tag available locally, not fetching.
+        else
+            git fetch origin && echo Fetched from origin || echo Could not fetch
+        fi
         last_dockerfile="$last_tag"-${DOCKERFILE_PATH}
         if git show "$last_tag"^:${DOCKERFILE_PATH} >"$last_dockerfile"; then
             echo Copied last dockerfile to $last_dockerfile
-            if ! diff "${DOCKERFILE_PATH}" "$last_dockerfile"; then
+            # diff returns True if there is *no* difference
+            if diff "${DOCKERFILE_PATH}" "$last_dockerfile"; then
                 echo "Dockerfile $last_tag:$DOCKERFILE_PATH changed from"
                 echo "$current_tag:$DOCKERFILE_PATH, pulling: ${NAME}"
-                docker pull "${NAME}"
-                exit
+                # try pulling the last version of the image
+                last_image="${NAME}"-"${last_tag/v/}"  # remove prefixed 'v'
+                if docker pull "${last_image}"; then
+                    echo "Pulled image ${last_image} successfully, skipping build."
+                    docker tag "${last_image}" "${NAME}"
+                    exit
+                else
+                    echo "Failed to pull ${last_image}, rebuilding."
+                fi
             else
                 echo "Dockerfile changed since last tag, rebuilding."
             fi
